name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: ['20', '22']
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Node Modules
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: yarn install --frozen-lockfile

    - name: Build
      run: npx lerna exec yarn

    - name: Test
      run: yarn test --silent --testPathIgnorePatterns "stream.test.ts" "cohort*.test.ts"
      env:
        API_KEY: ${{ secrets.API_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        EU_API_KEY: ${{ secrets.EU_API_KEY }}
        EU_SECRET_KEY: ${{ secrets.EU_SECRET_KEY }}
        MANAGEMENT_API_KEY: ${{ secrets.MANAGEMENT_API_KEY }}
